apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesStrategicMerge:
- replicas-patch.yaml

# replicas will be ignored because of the override of patchesStrategicMerge here
replicas:
  - name: vote
    count: 4

commonLabels:
  Project: awesomeProject
  env: staging