apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: replicas-patch.yaml

replicas:
  - name: vote
    count: 4

images:
  - name: riheel/vote
    newTag: V1

commonLabels:
  Project: awesomeProject
  env: staging